### ISSUE TITLE
tree display broken for hidden review

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#585]
Haven't tracked down the root cause for this yet, or confirmed for sure that it's not already fixed in master, but at least in 6107fe0e13215ad07ff839fc8c67ca1a11c90bc9  and 420deb6e3f62012993e2e7f54b12659fa31787ee  the tree display is broken for the hidden review, so all that you get is a count of incorrect relations and attributes and no visual pointers to the errors.

 TypeError: Cannot read property 'getPropertyValue' of null
    at Array._a.style (http://www.perseids.org/tools/arethusa-staging/bower_components/d3/d3.min.js:3:8841)
    at http://www.perseids.org/tools/arethusa-staging/dist/arethusa.min.js:15:12940
    at Object.q [as forEach] (http://www.perseids.org/tools/arethusa-staging/dist/arethusa_packages.min.js:12:386)
    at z (http://www.perseids.org/tools/arethusa-staging/dist/arethusa.min.js:15:12909)
    at http://www.perseids.org/tools/arethusa-staging/dist/arethusa.min.js:15:12800
    at Object.q [as forEach] (http://www.perseids.org/tools/arethusa-staging/dist/arethusa_packages.min.js:12:386)
    at y (http://www.perseids.org/tools/arethusa-staging/dist/arethusa.min.js:15:12742)
    at Object.fn (http://www.perseids.org/tools/arethusa-staging/dist/arethusa.min.js:15:18869)
    at h.$digest (http://www.perseids.org/tools/arethusa-staging/dist/arethusa_packages.min.js:113:454)
    at h.$apply (http://www.perseids.org/tools/arethusa-staging/dist/arethusa_packages.min.js:116:451)

**Comment by LFDM** [comment]
Works, but the conf file for hidden reviewing is broken.

The right conf option is to give the review plugin `"hideMode": true`.
It needs some refinement still though, but this will be another issue.
